### ISSUE TITLE
"Upgrade: websocket"  has to be all lower case(?)

### ISSUE THREAD

**Issue by Claus1** [Kai-Bailey/WebSock#5]
I use flutter and tokens from flutter contain 'upgrade: websocket', not "Upgrade: websocket".
I do not know who is right but it is a problem.
```
def _opening_handshake(self, client, data):
       ...
        if "Upgrade: websocket" not in tokens:
            return resp
       ...
```

**Comment by Haegi** [comment]
According to RFC 6455 the tokens should contain 'Upgrade: websocket' and 'Sec-WebSocket-Key'.
But since WebSock should support flutter as well, I will take care of this.

**Comment by Claus1** [comment]
Unfortunately this changes is not enough even for correct connection(initialization). 

> IOWebSocketChannel.connect('ws://localhost:1234');

But have no idea about why although pretty sure it is flutter errors. Other clients with the same code works with WebSock without problems.

**Comment by Haegi** [comment]
#8 WebSock now supports flutter :tada:

**Comment by Claus1** [comment]
@Haegi You mean in google they fixed errors in their IOWebSocketChannel?

**Comment by Claus1** [comment]
can not test the pull request without merging with master(

**Comment by Haegi** [comment]
@Claus1 version 1.0.4 is now merged

**Comment by Claus1** [comment]
I still got errors from Websock:

Traceback (most recent call last):
  File "/home/george/.vscode/extensions/ms-python.python-2020.2.64397/pythonFiles/lib/python/old_ptvsd/ptvsd/_vendored/pydevd/_pydevd_bundle/pydevd_additional_thread_info_regular.py", line 143, in set_additional_thread_info
    additional_info = thread.additional_info
AttributeError: 'NoneType' object has no attribute 'additional_info'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/george/.vscode/extensions/ms-python.python-2020.2.64397/pythonFiles/lib/python/old_ptvsd/ptvsd/_vendored/pydevd/_pydevd_bundle/pydevd_frame.py", line 709, in trace_dispatch
    self.do_wait_suspend(thread, frame, event, arg)
  File "/home/george/.vscode/extensions/ms-python.python-2020.2.64397/pythonFiles/lib/python/old_ptvsd/ptvsd/_vendored/pydevd/_pydevd_bundle/pydevd_frame.py", line 97, in do_wait_suspend
    self._args[0].do_wait_suspend(*args, **kwargs)
  File "/home/george/.vscode/extensions/ms-python.python-2020.2.64397/pythonFiles/lib/python/old_ptvsd/ptvsd/_vendored/pydevd/pydevd.py", line 1615, in do_wait_suspend
    with self._threads_suspended_single_notification.notify_thread_suspended(thread_id, stop_reason):
  File "/usr/lib/python3.6/contextlib.py", line 81, in __enter__
    return next(self.gen)
  File "/home/george/.vscode/extensions/ms-python.python-2020.2.64397/pythonFiles/lib/python/old_ptvsd/ptvsd/_vendored/pydevd/pydevd.py", line 360, in notify_thread_suspended
    with AbstractSingleNotificationBehavior.notify_thread_suspended(self, thread_id, stop_reason):
  File "/usr/lib/python3.6/contextlib.py", line 81, in __enter__
    return next(self.gen)
  File "/home/george/.vscode/extensions/ms-python.python-2020.2.64397/pythonFiles/lib/python/old_ptvsd/ptvsd/_vendored/pydevd/pydevd.py", line 308, in notify_thread_suspended
    self.send_suspend_notification(thread_id, stop_reason)
  File "/home/george/.vscode/extensions/ms-python.python-2020.2.64397/pythonFiles/lib/python/old_ptvsd/ptvsd/_vendored/pydevd/pydevd.py", line 354, in send_suspend_notification
    py_db.writer.add_command(py_db.cmd_factory.make_thread_suspend_single_notification(py_db, thread_id, stop_reason))
  File "/home/george/.vscode/extensions/ms-python.python-2020.2.64397/pythonFiles/lib/python/old_ptvsd/ptvsd/_vendored/pydevd/_pydevd_bundle/pydevd_net_command_factory_json.py", line 273, in make_thread_suspend_single_notification
    info = set_additional_thread_info(thread)
  File "/home/george/.vscode/extensions/ms-python.python-2020.2.64397/pythonFiles/lib/python/old_ptvsd/ptvsd/_vendored/pydevd/_pydevd_bundle/pydevd_additional_thread_info_regular.py", line 153, in set_additional_thread_info
    thread.additional_info = additional_info
AttributeError: 'NoneType' object has no attribute 'additional_info'

**Comment by Claus1** [comment]
++ ws.log

> INFO:MainThread
	Server is ready to accept
INFO:MainThread
	[IN]  CONNECTION: ('127.0.0.1', 1234)
INFO:MainThread
	Server is ready to accept
INFO:Thread-3
	[IN]  TEXT: ('127.0.0.1', 1234) - ''
CRITICAL:Thread-3
	Received Invalid Data Frame

**Comment by Haegi** [comment]
Please have a look at the [flutter example](https://github.com/Kai-Bailey/WebSock/blob/master/examples/flutter/flutter.md).
The loopback address (127.0.0.1) could be the cause for your problem.

**Comment by Claus1** [comment]
I do not use emulator, only Linux native flutter app. Initialization and sending first package server-to-client is ok. Sending client->server such json ['1','2','3', 3] causes 'Received Invalid Data Frame' and closing socket. Why and where is problem in Websock is not clear. I see only the message in console:
<socket.socket fd=24, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 1234), raddr=('127.0.0.1', 54486)> closed
and same ws.log about invalid frame.
I start server as below:
`ws = WebSocketServer("0.0.0.0", 1234, 
                    on_data_receive=on_data_receive,
                    ...)
ws.serve_forever()`

**Comment by Haegi** [comment]
@Claus1 
I added documentation on how to send arrays in flutter [here](https://github.com/Kai-Bailey/WebSock/blob/master/examples/flutter/flutter.md#flutter-array-payload).
